apiVersion: v1
kind: ResourceQuota
metadata:
  name: lab-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory }}
    pods: {{ .Values.quota.pods | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lab-limits
  namespace: {{ .Release.Namespace }}
spec:
  limits:
    - type: Container
      default: { cpu: 500m, memory: 512Mi }
      defaultRequest: { cpu: 100m, memory: 256Mi }
